-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 12:17:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pogoda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pogoda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pogoda` DEFAULT CHARACTER SET utf8 ;
USE `Pogoda` ;

-- -----------------------------------------------------
-- Table `Pogoda`.`station_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`station_data` (
  `id_stacji` INT NOT NULL,
  `stacja` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `nr` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_stacji`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`temperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`temperature` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `temperature` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_temperature_station_data_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_temperature_station_data`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`wind_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`wind_s` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `wind_speed` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_wind_s_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_wind_s_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`wind_d`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`wind_d` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `wind_direction` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_wind_d_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_wind_d_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`hum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`hum` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `humidity` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_hum_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_hum_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`air`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`air` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `air_pressure` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_air_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_air_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`rain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`rain` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `rainfall` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_rain_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_rain_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`eva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`eva` (
  `station_data_id_stacji` INT NOT NULL,
  `date_measurement` DATE NULL,
  `hour_measurement` DATE NULL,
  `evaporation` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_eva_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_eva_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`manager` (
  `station_data_id_stacji` INT NOT NULL,
  `degree` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surename` VARCHAR(45) NULL,
  PRIMARY KEY (`station_data_id_stacji`),
  INDEX `fk_manager_station_data1_idx` (`station_data_id_stacji` ASC),
  CONSTRAINT `fk_manager_station_data1`
    FOREIGN KEY (`station_data_id_stacji`)
    REFERENCES `Pogoda`.`station_data` (`id_stacji`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pogoda`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pogoda`.`Users` (
  `idUsers` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Permisson` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
